# Generated by Django 5.0.2 on 2025-07-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('sub_district', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('transferred', 'Transferred')], default='active', max_length=20)),
            ],
        ),
    ]
